ci: refactor release and upload process
Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -171,7 +171,6 @@ task:
   env:
     BIN: names
     RUST_BACKTRACE: 1
-    GITHUB_TOKEN: ENCRYPTED[55bcbfb4ebfdf487e0e0c404ea1fa3b21b3fb509f27062363d91110e2611795abd521815979ac2fa2c23300cbc3afa95]
   matrix:
     - matrix:
         - env:
@@ -189,7 +188,6 @@ task:
               - TARGET: x86_64-unknown-linux-musl
                 STRIP: x86_64-linux-musl-strip
             EXT: tar.gz
-            TYPE: application/gzip
           container:
             image: rustembedded/cross:$TARGET
           depends_on:
@@ -198,12 +196,11 @@ task:
           <<: *base_linux
           <<: *install_target_unix
           <<: *build_unix
-          archive_script: tar czf "${BIN}-${TARGET}.${EXT}" "${BIN}-${TARGET}"
+          archive_script: tar czf "$BIN-$TARGET.$EXT" "$BIN-$TARGET"
         - env:
             TARGET: x86_64-apple-darwin
             STRIP: strip
             EXT: zip
-            TYPE: application/zip
           osx_instance:
             image: catalina-base
           depends_on:
@@ -212,12 +209,11 @@ task:
           <<: *base_macos
           <<: *install_target_unix
           <<: *build_unix
-          archive_script: zip "${BIN}-${TARGET}" "${BIN}-${TARGET}"
+          archive_script: zip "$BIN-$TARGET" "$BIN-$TARGET"
         - env:
             TARGET: x86_64-unknown-freebsd
             STRIP: strip
             EXT: tar.gz
-            TYPE: application/gzip
           freebsd_instance:
             image_family: freebsd-11-4
           depends_on:
@@ -226,26 +222,14 @@ task:
           <<: *base_freebsd
           <<: *install_target_unix
           <<: *build_unix
-          archive_script: |
-            tar czf "${BIN}-${TARGET}.${EXT}" "${BIN}-${TARGET}"
-      sha256_script: |
-        ./.ci/sha256.sh "${BIN}-${TARGET}.${EXT}" \
-          > "${BIN}-${TARGET}.${EXT}.sha256"
-      binary_artifacts:
-        path: ${BIN}-${TARGET}.${EXT}
-        type: $TYPE
-      release_artifact_script: |
-        if [ -n "${CIRRUS_RELEASE:-}" ]; then
-          ./.ci/publish-artifact.sh "$CIRRUS_REPO_FULL_NAME" \
-            "$CIRRUS_RELEASE" "${BIN}-${TARGET}.${EXT}"
-          ./.ci/publish-artifact.sh "$CIRRUS_REPO_FULL_NAME" \
-            "$CIRRUS_RELEASE" "${BIN}-${TARGET}.${EXT}.sha256"
-        fi
+          archive_script: tar czf "$BIN-$TARGET.$EXT" "$BIN-$TARGET"
+      checksums_script: ./.ci/build-checksums.sh "$BIN-$TARGET.$EXT"
+      binaries_artifacts:
+        path: "$BIN-$TARGET.$EXT*"
       <<: *cleanup_before_upload_cache_unix
     - env:
         TARGET: x86_64-pc-windows-msvc
         EXT: zip
-        TYPE: application/zip
       windows_container:
         image: fnichol/windowsservercore:ltsc2019-vs2019-vctools
       depends_on:
@@ -256,25 +240,58 @@ task:
       <<: *build_windows
       archive_script: |
         Compress-Archive "$env:BIN-$env:TARGET.exe" "$env:BIN-$env:TARGET.$env:EXT"
-      sha256_script: |
-        .\.ci\sha256.ps1 "$env:BIN-$env:TARGET.$env:EXT" `
-          > "$env:BIN-$env:TARGET.$env:EXT.sha256"
-      binary_artifacts:
-        path: ${BIN}-${TARGET}.${EXT}
-        type: $TYPE
-      release_artifact_script: |
-        if (Test-Path env:CIRRUS_RELEASE) {
-          .\.ci\publish-artifact.ps1 "$env:CIRRUS_REPO_FULL_NAME" `
-            `"$env:CIRRUS_RELEASE" "$env:BIN-$env:TARGET.$env:EXT"
-          .\.ci\publish-artifact.ps1 "$env:CIRRUS_REPO_FULL_NAME" `
-            `"$env:CIRRUS_RELEASE" "$env:BIN-$env:TARGET.$env:EXT.sha256"
-        }
+      checksums_script: .\.ci\build-checksums.ps1 "$env:BIN-$env:TARGET.$env:EXT"
+      binaries_artifacts:
+        path: "$BIN-$TARGET.$EXT*"
       <<: *cleanup_before_upload_cache_windows
 
-docker_builder:
-  only_if: $CIRRUS_RELEASE != ''
+task:
+  name: release-version
+  env:
+    BIN: names
+    GITHUB_TOKEN: ENCRYPTED[55bcbfb4ebfdf487e0e0c404ea1fa3b21b3fb509f27062363d91110e2611795abd521815979ac2fa2c23300cbc3afa95]
+  only_if: $CIRRUS_TAG != ''
   depends_on:
+    - bin-build-names-x86_64-apple-darwin
+    - bin-build-names-x86_64-unknown-freebsd
+    - bin-build-names-aarch64-unknown-linux-gnu
+    - bin-build-names-arm-unknown-linux-gnueabihf
+    - bin-build-names-i686-unknown-linux-musl
     - bin-build-names-x86_64-unknown-linux-musl
+    - bin-build-names-i686-unknown-linux-gnu
+    - bin-build-names-x86_64-unknown-linux-gnu
+    - bin-build-names-x86_64-pc-windows-msvc
+  install_dependencies_script: apk add curl jo jq
+  create_github_release_script: |
+    if ! upload_url="$(
+      ./.ci/cirrus-release.sh gh_create_version_release \
+        "$CIRRUS_REPO_FULL_NAME" \
+        "$CIRRUS_TAG"
+    )"; then
+      echo "xxx Failed to create release" >&2
+      exit 1
+    fi
+    echo "$upload_url" > /tmp/upload_url
+  download_cirrus_artifacts_script: |
+    cr="$(readlink -f ./.ci/cirrus-release.sh)"
+    manifest="$(readlink -f ".ci/$BIN.manifest.txt")"
+    mkdir -p /tmp/release
+    cd /tmp/release
+    awk '{ print $2 }' "$manifest" | while read -r a; do
+      "$cr" ci_download "bin-build-$a/binaries/$a"
+      "$cr" ci_download "bin-build-$a/binaries/$a.md5"
+      "$cr" ci_download "bin-build-$a/binaries/$a.sha256"
+    done
+    cp "$manifest" .
+    ls -l "$BIN"*
+  upload_release_artifacts_script: |
+    url="$(cat /tmp/upload_url)"
+    ./.ci/cirrus-release.sh gh_upload_all "$url" /tmp/release
+
+docker_builder:
+  only_if: $CIRRUS_TAG != ''
+  depends_on:
+    - release-version
   env:
     IMAGE_NAME: fnichol/names
     BIN: names
@@ -282,7 +299,7 @@ docker_builder:
     DOCKER_PASSWORD: ENCRYPTED[12bfff137d45a5dfb76671cbd072338ef04c54cf0f6b7076eccb8eaee28812e412c1eaacb612312a535b7b255ab18a93]
   build_script: |
     ./.ci/build-docker-image.sh "$IMAGE_NAME" "$BIN" "${CIRRUS_TAG#v}"
-  login_script: >
+  login_script: |
     echo "$DOCKER_PASSWORD" \
       | docker login --username "$DOCKER_USERNAME" --password-stdin
   push_script:
